from pyspark.sql.types import *

# Define the schema for the DataFrame

example_spark = StructType([
    StructField("Country name", StringType(), True),
    StructField("Series name", StringType(), True),
    StructField("Value", FloatType(), True),
    StructField("value_percentile", FloatType(), True)
])

example_pandas = {
    "Country name": str,
    "Series name": str,
    "Value": float,    
    "value_percentile": float
}

fdic_banks_pandas = {
    "fdic_certificate_number": str,
    "institution_name": str,
    "state_name": str,
    "fdic_id": str,
    "docket": str,
    "active": bool,
    "address": str,
    "total_assets": str,
    "bank_charter_class": str,
    "change_code_1": str,
    "change_code_2": str,
    "change_code_3": str,
    "change_code_4": str,
    "change_code_5": str,
    "change_code_6": str,
    "change_code_7": str,
    "change_code_8": str,
    "change_code_9": str,
    "change_code_10": str,
    "change_code_11": str,
    "change_code_12": str,
    "change_code_13": str,
    "change_code_14": str,
    "change_code_15": str,
    "occ_charter": str,
    "chartering_agency": str,
    "conservatorship": bool,
    "city": str,
    "category_code": str,
    "county_fips_code": str,
    "county_name": str,
    "established_date": str,
    "last_updated": str,
    "effective_date": str,
    "end_effective_date": str,
    "denovo_institute": str,
    "total_deposits": str,
    "equity_capital": str,
    "fdic_geo_region": str,
    "fdic_supervisory_region": str,
    "fdic_supervisory_region_code": str,
    "fed_reserve_district": str,
    "fed_reserve_district_id": str,
    "fed_reserve_unique_id": str,
    "federal_charter": bool,
    "fdic_field_office": str,
    "iba": bool,
    "inactive_flag": bool,
    "insurance_fund_membership": str,
    "secondary_insurance_fund": str,
    "deposit_insurance_date": str,
    "credit_card_institution": str,
    "bank_insurance_fund_member": bool,
    "insured_commercial_bank": bool,
    "deposit_insurance_fund_member": bool,
    "fdic_insured": bool,
    "saif_insured": bool,
    "insured_savings_institute": bool,
    "new_cert_number": str,
    "oakar_institute": bool,
    "ots_region": str,
    "last_structural_change": str,
    "qbp_region": str,
    "regulator": str,
    "report_date": str,
    "reporting_period_end_date": str,
    "state_chartered": bool,
    "return_on_assets": str,
    "roa_quarterly": str,
    "roa_pretax": str,
    "row_pretax_quarterly": str,
    "return_on_equity": str,
    "roe_quarterly": str,
    "run_date": str,
    "sasser_institute": bool,
    "law_sasser": bool,
    "state": str,
    "state_fips_code": str,
    "trade_name_1": str,
    "trade_name_2": str,
    "trade_name_3": str,
    "trade_name_4": str,
    "trade_name_5": str,
    "trade_name_6": str,
    "zip_code": str,
    "occ_district": str,
    "ultimate_cert_number": str,
    "cfpb_supervisory_flag": bool,
    "cfpb_supervisory_start_date": str,
    "cfpb_supervisory_end_date": str,
    "offices_count": str,
    "parent_fdic_cert": str,
    "parent_parcert": str,
    "high_holder_city": str,
    "total_domestic_deposits": str,
    "ffiec_call_report_filer": str,
    "holding_company_flag": str,
    "ag_lending_flag": str,
    "ownership_type": str,
    "top_holder": str,
    "net_income": str,
    "quarterly_net_income": str,
    "office_count_domestic": str,
    "office_count_foreign": str,
    "office_count_us_territories": str,
    "rssd_id": str,
    "holding_company_state": str,
    "subchap_s_indicator": str,
    "trust_powers_status": str,
    "asset_concentration_hierarchy": str,
    "primary_specialization": str,
    "csa_name": str,
    "csa_fips_code": str,
    "csa_indicator": bool,
    "cbsa_name": str,
    "cbsa_fips_code": str,
    "cbsa_metro_flag": bool,
    "cbsa_micro_flag": bool,
    "cbsa_division_name": str,
    "cbsa_division_fips_code": str,
    "cbsa_division_flag": bool
}

fdic_banks_spark = StructType([
    StructField("fdic_certificate_number", StringType(), True),
    StructField("institution_name", StringType(), True),
    StructField("state_name", StringType(), True),
    StructField("fdic_id", StringType(), True),
    StructField("docket", StringType(), True),
    StructField("active", BooleanType(), True),
    StructField("address", StringType(), True),
    StructField("total_assets", StringType(), True),
    StructField("bank_charter_class", StringType(), True),
    StructField("change_code_1", StringType(), True),
    StructField("change_code_2", StringType(), True),
    StructField("change_code_3", StringType(), True),
    StructField("change_code_4", StringType(), True),
    StructField("change_code_5", StringType(), True),
    StructField("change_code_6", StringType(), True),
    StructField("change_code_7", StringType(), True),
    StructField("change_code_8", StringType(), True),
    StructField("change_code_9", StringType(), True),
    StructField("change_code_10", StringType(), True),
    StructField("change_code_11", StringType(), True),
    StructField("change_code_12", StringType(), True),
    StructField("change_code_13", StringType(), True),
    StructField("change_code_14", StringType(), True),
    StructField("change_code_15", StringType(), True),
    StructField("occ_charter", StringType(), True),
    StructField("chartering_agency", StringType(), True),
    StructField("conservatorship", BooleanType(), True),
    StructField("city", StringType(), True),
    StructField("category_code", StringType(), True),
    StructField("county_fips_code", StringType(), True),
    StructField("county_name", StringType(), True),
    StructField("established_date", StringType(), True),
    StructField("last_updated", StringType(), True),
    StructField("effective_date", StringType(), True),
    StructField("end_effective_date", StringType(), True),
    StructField("denovo_institute", StringType(), True),
    StructField("total_deposits", StringType(), True),
    StructField("equity_capital", StringType(), True),
    StructField("fdic_geo_region", StringType(), True),
    StructField("fdic_supervisory_region", StringType(), True),
    StructField("fdic_supervisory_region_code", StringType(), True),
    StructField("fed_reserve_district", StringType(), True),
    StructField("fed_reserve_district_id", StringType(), True),
    StructField("fed_reserve_unique_id", StringType(), True),
    StructField("federal_charter", BooleanType(), True),
    StructField("fdic_field_office", StringType(), True),
    StructField("iba", BooleanType(), True),
    StructField("inactive_flag", BooleanType(), True),
    StructField("insurance_fund_membership", StringType(), True),
    StructField("secondary_insurance_fund", StringType(), True),
    StructField("deposit_insurance_date", StringType(), True),
    StructField("credit_card_institution", StringType(), True),
    StructField("bank_insurance_fund_member", BooleanType(), True),
    StructField("insured_commercial_bank", BooleanType(), True),
    StructField("deposit_insurance_fund_member", BooleanType(), True),
    StructField("fdic_insured", BooleanType(), True),
    StructField("saif_insured", BooleanType(), True),
    StructField("insured_savings_institute", BooleanType(), True),
    StructField("new_cert_number", StringType(), True),
    StructField("oakar_institute", BooleanType(), True),
    StructField("ots_region", StringType(), True),
    StructField("last_structural_change", StringType(), True),
    StructField("qbp_region", StringType(), True),
    StructField("regulator", StringType(), True),
    StructField("report_date", StringType(), True),
    StructField("reporting_period_end_date", StringType(), True),
    StructField("state_chartered", BooleanType(), True),
    StructField("return_on_assets", StringType(), True),
    StructField("roa_quarterly", StringType(), True),
    StructField("roa_pretax", StringType(), True),
    StructField("row_pretax_quarterly", StringType(), True),
    StructField("return_on_equity", StringType(), True),
    StructField("roe_quarterly", StringType(), True),
    StructField("run_date", StringType(), True),
    StructField("sasser_institute", BooleanType(), True),
    StructField("law_sasser", BooleanType(), True),
    StructField("state", StringType(), True),
    StructField("state_fips_code", StringType(), True),
    StructField("trade_name_1", StringType(), True),
    StructField("trade_name_2", StringType(), True),
    StructField("trade_name_3", StringType(), True),
    StructField("trade_name_4", StringType(), True),
    StructField("trade_name_5", StringType(), True),
    StructField("trade_name_6", StringType(), True),
    StructField("zip_code", StringType(), True),
    StructField("occ_district", StringType(), True),
    StructField("ultimate_cert_number", StringType(), True),
    StructField("cfpb_supervisory_flag", BooleanType(), True),
    StructField("cfpb_supervisory_start_date", StringType(), True),
    StructField("cfpb_supervisory_end_date", StringType(), True),
    StructField("offices_count", StringType(), True),
    StructField("parent_fdic_cert", StringType(), True),
    StructField("parent_parcert", StringType(), True),
    StructField("high_holder_city", StringType(), True),
    StructField("total_domestic_deposits", StringType(), True),
    StructField("ffiec_call_report_filer", StringType(), True),
    StructField("holding_company_flag", StringType(), True),
    StructField("ag_lending_flag", StringType(), True),
    StructField("ownership_type", StringType(), True),
    StructField("top_holder", StringType(), True),
    StructField("net_income", StringType(), True),
    StructField("quarterly_net_income", StringType(), True),
    StructField("office_count_domestic", StringType(), True),
    StructField("office_count_foreign", StringType(), True),
    StructField("office_count_us_territories", StringType(), True),
    StructField("rssd_id", StringType(), True),
    StructField("holding_company_state", StringType(), True),
    StructField("subchap_s_indicator", StringType(), True),
    StructField("trust_powers_status", StringType(), True),
    StructField("asset_concentration_hierarchy", StringType(), True),
    StructField("primary_specialization", StringType(), True),
    StructField("csa_name", StringType(), True),
    StructField("csa_fips_code", StringType(), True),
    StructField("csa_indicator", BooleanType(), True),
    StructField("cbsa_name", StringType(), True),
    StructField("cbsa_fips_code", StringType(), True),
    StructField("cbsa_metro_flag", BooleanType(), True),
    StructField("cbsa_micro_flag", BooleanType(), True),
    StructField("cbsa_division_name", StringType(), True),
    StructField("cbsa_division_fips_code", StringType(), True),
    StructField("cbsa_division_flag", BooleanType(), True)
])

fdic_banks_psql = {
    "fdic_certificate_number": "VARCHAR",
    "institution_name": "VARCHAR",
    "state_name": "VARCHAR",
    "fdic_id": "VARCHAR",
    "docket": "VARCHAR",
    "active": "BOOLEAN",
    "address": "VARCHAR",
    "total_assets": "VARCHAR",
    "bank_charter_class": "VARCHAR",
    "change_code_1": "VARCHAR",
    "change_code_2": "VARCHAR",
    "change_code_3": "VARCHAR",
    "change_code_4": "VARCHAR",
    "change_code_5": "VARCHAR",
    "change_code_6": "VARCHAR",
    "change_code_7": "VARCHAR",
    "change_code_8": "VARCHAR",
    "change_code_9": "VARCHAR",
    "change_code_10": "VARCHAR",
    "change_code_11": "VARCHAR",
    "change_code_12": "VARCHAR",
    "change_code_13": "VARCHAR",
    "change_code_14": "VARCHAR",
    "change_code_15": "VARCHAR",
    "occ_charter": "VARCHAR",
    "chartering_agency": "VARCHAR",
    "conservatorship": "BOOLEAN",
    "city": "VARCHAR",
    "category_code": "VARCHAR",
    "county_fips_code": "VARCHAR",
    "county_name": "VARCHAR",
    "established_date": "VARCHAR",
    "last_updated": "VARCHAR",
    "effective_date": "VARCHAR",
    "end_effective_date": "VARCHAR",
    "denovo_institute": "VARCHAR",
    "total_deposits": "VARCHAR",
    "equity_capital": "VARCHAR",
    "fdic_geo_region": "VARCHAR",
    "fdic_supervisory_region": "VARCHAR",
    "fdic_supervisory_region_code": "VARCHAR",
    "fed_reserve_district": "VARCHAR",
    "fed_reserve_district_id": "VARCHAR",
    "fed_reserve_unique_id": "VARCHAR",
    "federal_charter": "BOOLEAN",
    "fdic_field_office": "VARCHAR",
    "iba": "BOOLEAN",
    "inactive_flag": "BOOLEAN",
    "insurance_fund_membership": "VARCHAR",
    "secondary_insurance_fund": "VARCHAR",
    "deposit_insurance_date": "VARCHAR",
    "credit_card_institution": "VARCHAR",
    "bank_insurance_fund_member": "BOOLEAN",
    "insured_commercial_bank": "BOOLEAN",
    "deposit_insurance_fund_member": "BOOLEAN",
    "fdic_insured": "BOOLEAN",
    "saif_insured": "BOOLEAN",
    "insured_savings_institute": "BOOLEAN",
    "new_cert_number": "VARCHAR",
    "oakar_institute": "BOOLEAN",
    "ots_region": "VARCHAR",
    "last_structural_change": "VARCHAR",
    "qbp_region": "VARCHAR",
    "regulator": "VARCHAR",
    "report_date": "VARCHAR",
    "reporting_period_end_date": "VARCHAR",
    "state_chartered": "BOOLEAN",
    "return_on_assets": "VARCHAR",
    "roa_quarterly": "VARCHAR",
    "roa_pretax": "VARCHAR",
    "row_pretax_quarterly": "VARCHAR",
    "return_on_equity": "VARCHAR",
    "roe_quarterly": "VARCHAR",
    "run_date": "VARCHAR",
    "sasser_institute": "BOOLEAN",
    "law_sasser": "BOOLEAN",
    "state": "VARCHAR",
    "state_fips_code": "VARCHAR",
    "trade_name_1": "VARCHAR",
    "trade_name_2": "VARCHAR",
    "trade_name_3": "VARCHAR",
    "trade_name_4": "VARCHAR",
    "trade_name_5": "VARCHAR",
    "trade_name_6": "VARCHAR",
    "zip_code": "VARCHAR",
    "occ_district": "VARCHAR",
    "ultimate_cert_number": "VARCHAR",
    "cfpb_supervisory_flag": "BOOLEAN",
    "cfpb_supervisory_start_date": "VARCHAR",
    "cfpb_supervisory_end_date": "VARCHAR",
    "offices_count": "VARCHAR",
    "parent_fdic_cert": "VARCHAR",
    "parent_parcert": "VARCHAR",
    "high_holder_city": "VARCHAR",
    "total_domestic_deposits": "VARCHAR",
    "ffiec_call_report_filer": "VARCHAR",
    "holding_company_flag": "VARCHAR",
    "ag_lending_flag": "VARCHAR",
    "ownership_type": "VARCHAR",
    "top_holder": "VARCHAR",
    "net_income": "VARCHAR",
    "quarterly_net_income": "VARCHAR",
    "office_count_domestic": "VARCHAR",
    "office_count_foreign": "VARCHAR",
    "office_count_us_territories": "VARCHAR",
    "rssd_id": "VARCHAR",
    "holding_company_state": "VARCHAR",
    "subchap_s_indicator": "VARCHAR",
    "trust_powers_status": "VARCHAR",
    "asset_concentration_hierarchy": "VARCHAR",
    "primary_specialization": "VARCHAR",
    "csa_name": "VARCHAR",
    "csa_fips_code": "VARCHAR",
    "csa_indicator": "BOOLEAN",
    "cbsa_name": "VARCHAR",
    "cbsa_fips_code": "VARCHAR",
    "cbsa_metro_flag": "BOOLEAN",
    "cbsa_micro_flag": "BOOLEAN",
    "cbsa_division_name": "VARCHAR",
    "cbsa_division_fips_code": "VARCHAR",
    "cbsa_division_flag": "BOOLEAN"
}
